/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../../../core/index.js";
import * as ProofStateAPI from "../../../../../index.js";
import {
  mergeHeaders,
  mergeOnlyDefinedHeaders,
} from "../../../../../../core/headers.js";
import * as errors from "../../../../../../errors/index.js";

export declare namespace Dashboards {
  export interface Options {
    environment: core.Supplier<string>;
    /** Specify a custom URL to connect the client to. */
    baseUrl?: core.Supplier<string>;
    username?: core.Supplier<string | undefined>;
    password?: core.Supplier<string | undefined>;
    /** Override the X-ProofState-Sdk-Name header */
    xProofStateSdkName?: core.Supplier<string | undefined>;
    /** Override the X-ProofState-Sdk-Version header */
    xProofStateSdkVersion?: core.Supplier<string | undefined>;
    /** Override the X-ProofState-Public-Key header */
    xProofStatePublicKey?: core.Supplier<string | undefined>;
    /** Additional headers to include in requests. */
    headers?: Record<
      string,
      string | core.Supplier<string | null | undefined> | null | undefined
    >;
  }

  export interface RequestOptions {
    /** The maximum time to wait for a response in seconds. */
    timeoutInSeconds?: number;
    /** The number of times to retry the request. Defaults to 2. */
    maxRetries?: number;
    /** A hook to abort the request. */
    abortSignal?: AbortSignal;
    /** Override the X-ProofState-Sdk-Name header */
    xProofStateSdkName?: string | undefined;
    /** Override the X-ProofState-Sdk-Version header */
    xProofStateSdkVersion?: string | undefined;
    /** Override the X-ProofState-Public-Key header */
    xProofStatePublicKey?: string | undefined;
    /** Additional query string parameters to include in the request. */
    queryParams?: Record<string, unknown>;
    /** Additional headers to include in the request. */
    headers?: Record<
      string,
      string | core.Supplier<string | null | undefined> | null | undefined
    >;
  }
}

export class Dashboards {
  protected readonly _options: Dashboards.Options;

  constructor(_options: Dashboards.Options) {
    this._options = _options;
  }

  /**
   * List dashboards in the project, ordered by most recently updated
   * first.
   *
   * @param {ProofStateAPI.unstable.ListDashboardsRequest} request
   * @param {Dashboards.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.unstable.BadRequestError}
   * @throws {@link ProofStateAPI.unstable.UnauthorizedError}
   * @throws {@link ProofStateAPI.unstable.AccessDeniedError}
   * @throws {@link ProofStateAPI.unstable.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.unstable.TooManyRequestsError}
   * @throws {@link ProofStateAPI.unstable.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.dashboards.list()
   */
  public list(
    request: ProofStateAPI.unstable.ListDashboardsRequest = {},
    requestOptions?: Dashboards.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.unstable.DashboardList> {
    return core.HttpResponsePromise.fromPromise(
      this.__list(request, requestOptions),
    );
  }

  private async __list(
    request: ProofStateAPI.unstable.ListDashboardsRequest = {},
    requestOptions?: Dashboards.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.unstable.DashboardList>> {
    const { page, limit } = request;
    const _queryParams: Record<
      string,
      string | string[] | object | object[] | null
    > = {};
    if (page != null) {
      _queryParams["page"] = page.toString();
    }

    if (limit != null) {
      _queryParams["limit"] = limit.toString();
    }

    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/unstable/dashboards",
      ),
      method: "GET",
      headers: _headers,
      queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.unstable.DashboardList,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.unstable.BadRequestError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.unstable.UnauthorizedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.unstable.AccessDeniedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.unstable.MethodNotAllowedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.unstable.TooManyRequestsError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.unstable.InternalServerError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/unstable/dashboards.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Create a dashboard.
   *
   * @param {ProofStateAPI.unstable.CreateDashboardRequest} request
   * @param {Dashboards.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.unstable.BadRequestError}
   * @throws {@link ProofStateAPI.unstable.UnauthorizedError}
   * @throws {@link ProofStateAPI.unstable.AccessDeniedError}
   * @throws {@link ProofStateAPI.unstable.NotFoundError}
   * @throws {@link ProofStateAPI.unstable.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.unstable.TooManyRequestsError}
   * @throws {@link ProofStateAPI.unstable.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.dashboards.create({
   *         name: "name",
   *         description: undefined,
   *         definition: undefined,
   *         filters: undefined
   *     })
   */
  public create(
    request: ProofStateAPI.unstable.CreateDashboardRequest,
    requestOptions?: Dashboards.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.unstable.Dashboard> {
    return core.HttpResponsePromise.fromPromise(
      this.__create(request, requestOptions),
    );
  }

  private async __create(
    request: ProofStateAPI.unstable.CreateDashboardRequest,
    requestOptions?: Dashboards.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.unstable.Dashboard>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/unstable/dashboards",
      ),
      method: "POST",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.unstable.Dashboard,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.unstable.BadRequestError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.unstable.UnauthorizedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.unstable.AccessDeniedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.unstable.NotFoundError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.unstable.MethodNotAllowedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.unstable.TooManyRequestsError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.unstable.InternalServerError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling POST /api/public/unstable/dashboards.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Get a dashboard by id.
   *
   * @param {string} dashboardId
   * @param {Dashboards.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.unstable.BadRequestError}
   * @throws {@link ProofStateAPI.unstable.UnauthorizedError}
   * @throws {@link ProofStateAPI.unstable.AccessDeniedError}
   * @throws {@link ProofStateAPI.unstable.NotFoundError}
   * @throws {@link ProofStateAPI.unstable.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.unstable.TooManyRequestsError}
   * @throws {@link ProofStateAPI.unstable.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.dashboards.get("dashboardId")
   */
  public get(
    dashboardId: string,
    requestOptions?: Dashboards.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.unstable.Dashboard> {
    return core.HttpResponsePromise.fromPromise(
      this.__get(dashboardId, requestOptions),
    );
  }

  private async __get(
    dashboardId: string,
    requestOptions?: Dashboards.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.unstable.Dashboard>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/unstable/dashboards/${encodeURIComponent(dashboardId)}`,
      ),
      method: "GET",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.unstable.Dashboard,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.unstable.BadRequestError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.unstable.UnauthorizedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.unstable.AccessDeniedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.unstable.NotFoundError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.unstable.MethodNotAllowedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.unstable.TooManyRequestsError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.unstable.InternalServerError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/unstable/dashboards/{dashboardId}.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Update a dashboard's name, description, definition, or filters.
   *
   * @param {string} dashboardId
   * @param {ProofStateAPI.unstable.UpdateDashboardRequest} request
   * @param {Dashboards.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.unstable.BadRequestError}
   * @throws {@link ProofStateAPI.unstable.UnauthorizedError}
   * @throws {@link ProofStateAPI.unstable.AccessDeniedError}
   * @throws {@link ProofStateAPI.unstable.NotFoundError}
   * @throws {@link ProofStateAPI.unstable.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.unstable.TooManyRequestsError}
   * @throws {@link ProofStateAPI.unstable.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.dashboards.update("dashboardId", {
   *         name: undefined,
   *         description: undefined,
   *         definition: undefined,
   *         filters: undefined
   *     })
   */
  public update(
    dashboardId: string,
    request: ProofStateAPI.unstable.UpdateDashboardRequest,
    requestOptions?: Dashboards.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.unstable.Dashboard> {
    return core.HttpResponsePromise.fromPromise(
      this.__update(dashboardId, request, requestOptions),
    );
  }

  private async __update(
    dashboardId: string,
    request: ProofStateAPI.unstable.UpdateDashboardRequest,
    requestOptions?: Dashboards.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.unstable.Dashboard>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/unstable/dashboards/${encodeURIComponent(dashboardId)}`,
      ),
      method: "PATCH",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.unstable.Dashboard,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.unstable.BadRequestError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.unstable.UnauthorizedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.unstable.AccessDeniedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.unstable.NotFoundError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.unstable.MethodNotAllowedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.unstable.TooManyRequestsError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.unstable.InternalServerError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling PATCH /api/public/unstable/dashboards/{dashboardId}.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Delete a dashboard.
   *
   * @param {string} dashboardId
   * @param {Dashboards.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.unstable.BadRequestError}
   * @throws {@link ProofStateAPI.unstable.UnauthorizedError}
   * @throws {@link ProofStateAPI.unstable.AccessDeniedError}
   * @throws {@link ProofStateAPI.unstable.NotFoundError}
   * @throws {@link ProofStateAPI.unstable.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.unstable.TooManyRequestsError}
   * @throws {@link ProofStateAPI.unstable.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.dashboards.delete("dashboardId")
   */
  public delete(
    dashboardId: string,
    requestOptions?: Dashboards.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.unstable.DeleteDashboardResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__delete(dashboardId, requestOptions),
    );
  }

  private async __delete(
    dashboardId: string,
    requestOptions?: Dashboards.RequestOptions,
  ): Promise<
    core.WithRawResponse<ProofStateAPI.unstable.DeleteDashboardResponse>
  > {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/unstable/dashboards/${encodeURIComponent(dashboardId)}`,
      ),
      method: "DELETE",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.unstable.DeleteDashboardResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.unstable.BadRequestError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.unstable.UnauthorizedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.unstable.AccessDeniedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.unstable.NotFoundError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.unstable.MethodNotAllowedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.unstable.TooManyRequestsError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.unstable.InternalServerError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling DELETE /api/public/unstable/dashboards/{dashboardId}.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Add a placement to a dashboard grid (see `DashboardPlacement` for
   * grid semantics).
   *
   * `id` and the position fields are optional: when omitted, the
   * placement gets a server-generated id and is appended below all
   * existing tiles as a 6x6 tile. Returns the created placement.
   *
   * The referenced widget must exist in the same project or be a
   * ProofState-managed widget. The API returns `409` if a placement with
   * the same `id` already exists on the dashboard.
   *
   * @param {string} dashboardId
   * @param {ProofStateAPI.unstable.CreateDashboardPlacementRequest} request
   * @param {Dashboards.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.unstable.BadRequestError}
   * @throws {@link ProofStateAPI.unstable.UnauthorizedError}
   * @throws {@link ProofStateAPI.unstable.AccessDeniedError}
   * @throws {@link ProofStateAPI.unstable.NotFoundError}
   * @throws {@link ProofStateAPI.unstable.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.unstable.ConflictError}
   * @throws {@link ProofStateAPI.unstable.TooManyRequestsError}
   * @throws {@link ProofStateAPI.unstable.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.dashboards.addPlacement("dashboardId", {
   *         type: "widget",
   *         id: undefined,
   *         widgetId: "widgetId",
   *         x: undefined,
   *         y: undefined,
   *         width: undefined,
   *         height: undefined
   *     })
   */
  public addPlacement(
    dashboardId: string,
    request: ProofStateAPI.unstable.CreateDashboardPlacementRequest,
    requestOptions?: Dashboards.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.unstable.DashboardPlacement> {
    return core.HttpResponsePromise.fromPromise(
      this.__addPlacement(dashboardId, request, requestOptions),
    );
  }

  private async __addPlacement(
    dashboardId: string,
    request: ProofStateAPI.unstable.CreateDashboardPlacementRequest,
    requestOptions?: Dashboards.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.unstable.DashboardPlacement>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/unstable/dashboards/${encodeURIComponent(dashboardId)}/placements`,
      ),
      method: "POST",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.unstable.DashboardPlacement,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.unstable.BadRequestError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.unstable.UnauthorizedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.unstable.AccessDeniedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.unstable.NotFoundError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.unstable.MethodNotAllowedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 409:
          throw new ProofStateAPI.unstable.ConflictError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.unstable.TooManyRequestsError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.unstable.InternalServerError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling POST /api/public/unstable/dashboards/{dashboardId}/placements.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Move or resize a placement. All fields are optional; at least one is
   * required. Omitted fields keep their current value. The placement's
   * content (widget/preset reference) and id cannot change — delete and
   * re-add the placement to swap content. Returns the updated placement.
   *
   * @param {string} dashboardId
   * @param {string} placementId
   * @param {ProofStateAPI.unstable.UpdateDashboardPlacementRequest} request
   * @param {Dashboards.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.unstable.BadRequestError}
   * @throws {@link ProofStateAPI.unstable.UnauthorizedError}
   * @throws {@link ProofStateAPI.unstable.AccessDeniedError}
   * @throws {@link ProofStateAPI.unstable.NotFoundError}
   * @throws {@link ProofStateAPI.unstable.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.unstable.TooManyRequestsError}
   * @throws {@link ProofStateAPI.unstable.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.dashboards.updatePlacement("dashboardId", "placementId", {
   *         x: undefined,
   *         y: undefined,
   *         width: undefined,
   *         height: undefined
   *     })
   */
  public updatePlacement(
    dashboardId: string,
    placementId: string,
    request: ProofStateAPI.unstable.UpdateDashboardPlacementRequest,
    requestOptions?: Dashboards.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.unstable.DashboardPlacement> {
    return core.HttpResponsePromise.fromPromise(
      this.__updatePlacement(dashboardId, placementId, request, requestOptions),
    );
  }

  private async __updatePlacement(
    dashboardId: string,
    placementId: string,
    request: ProofStateAPI.unstable.UpdateDashboardPlacementRequest,
    requestOptions?: Dashboards.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.unstable.DashboardPlacement>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/unstable/dashboards/${encodeURIComponent(dashboardId)}/placements/${encodeURIComponent(placementId)}`,
      ),
      method: "PATCH",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.unstable.DashboardPlacement,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.unstable.BadRequestError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.unstable.UnauthorizedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.unstable.AccessDeniedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.unstable.NotFoundError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.unstable.MethodNotAllowedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.unstable.TooManyRequestsError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.unstable.InternalServerError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling PATCH /api/public/unstable/dashboards/{dashboardId}/placements/{placementId}.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Remove a placement from a dashboard grid without deleting the referenced widget.
   *
   * @param {string} dashboardId
   * @param {string} placementId
   * @param {Dashboards.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.unstable.BadRequestError}
   * @throws {@link ProofStateAPI.unstable.UnauthorizedError}
   * @throws {@link ProofStateAPI.unstable.AccessDeniedError}
   * @throws {@link ProofStateAPI.unstable.NotFoundError}
   * @throws {@link ProofStateAPI.unstable.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.unstable.TooManyRequestsError}
   * @throws {@link ProofStateAPI.unstable.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.dashboards.deletePlacement("dashboardId", "placementId")
   */
  public deletePlacement(
    dashboardId: string,
    placementId: string,
    requestOptions?: Dashboards.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.unstable.DeleteDashboardPlacementResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__deletePlacement(dashboardId, placementId, requestOptions),
    );
  }

  private async __deletePlacement(
    dashboardId: string,
    placementId: string,
    requestOptions?: Dashboards.RequestOptions,
  ): Promise<
    core.WithRawResponse<ProofStateAPI.unstable.DeleteDashboardPlacementResponse>
  > {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/unstable/dashboards/${encodeURIComponent(dashboardId)}/placements/${encodeURIComponent(placementId)}`,
      ),
      method: "DELETE",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.unstable.DeleteDashboardPlacementResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.unstable.BadRequestError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.unstable.UnauthorizedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.unstable.AccessDeniedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.unstable.NotFoundError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.unstable.MethodNotAllowedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.unstable.TooManyRequestsError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.unstable.InternalServerError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling DELETE /api/public/unstable/dashboards/{dashboardId}/placements/{placementId}.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  protected async _getAuthorizationHeader(): Promise<string | undefined> {
    const username = await core.Supplier.get(this._options.username);
    const password = await core.Supplier.get(this._options.password);
    if (username != null && password != null) {
      return core.BasicAuth.toAuthorizationHeader({
        username: username,
        password: password,
      });
    }

    return undefined;
  }
}
