/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface PaginatedLlmConnections {
  data: ProofStateAPI.LlmConnection[];
  meta: ProofStateAPI.utils.MetaResponse;
}
