/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface BooleanEvaluationRuleFilter {
  /** Column to filter on. */
  column: string;
  operator: ProofStateAPI.EvaluationRuleBooleanFilterOperator;
  value: boolean;
}
