/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface DateTimeEvaluationRuleFilter {
  /** Column to filter on. */
  column: string;
  /** Comparison operator for datetime values. */
  operator: ProofStateAPI.EvaluationRuleNumberFilterOperator;
  /** Datetime value to compare against. */
  value: string;
}
