/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface EvaluationRuleReadFilterWithKey
  extends ProofStateAPI.EvaluationRuleReadFilterBase {
  /** Stored object or legacy filter key. */
  key: string;
}
