/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

/**
 * **Deprecated:** Connects one prompt variable to data from a legacy trace or dataset evaluation rule.
 *
 * `proofstateObject` selects the object kind. `objectName` separately selects a named observation and is `null` for trace and dataset-item mappings.
 *
 * @example
 *     {
 *         mappingType: "legacy",
 *         variable: "input",
 *         proofstateObject: ProofStateAPI.LegacyEvaluationObject.Trace,
 *         objectName: null,
 *         source: "input"
 *     }
 *
 * @example
 *     {
 *         mappingType: "legacy",
 *         variable: "output",
 *         proofstateObject: ProofStateAPI.LegacyEvaluationObject.Generation,
 *         objectName: "answer-generation",
 *         source: "output",
 *         jsonPath: "$.answer"
 *     }
 */
export interface LegacyPromptVariableMapping {
  /** Explicitly marks this as a legacy mapping. */
  mappingType: "legacy";
  /** Prompt variable name without braces. */
  variable: string;
  /** Legacy object kind selected as the mapping source. */
  proofstateObject: ProofStateAPI.LegacyEvaluationObject;
  /** Observation name to match, or `null` when `proofstateObject` is `trace` or `dataset_item`. */
  objectName: string | null;
  /** Field selected from the legacy object. */
  source: string;
  /** Optional JSONPath selector applied to the selected field. */
  jsonPath?: string;
}
