/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface NullEvaluationRuleFilter {
  /** Column to filter on, for example `parentObservationId`. */
  column: string;
  operator: ProofStateAPI.EvaluationRuleNullFilterOperator;
  /** Required empty-string placeholder used by the runtime filter contract. */
  value: "";
}
