/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

/**
 * Connects one prompt variable to source data.
 */
export type PromptVariableMapping =
  | ProofStateAPI.PromptVariableMappingRead
  | ProofStateAPI.LegacyPromptVariableMapping;
