/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface PublicEvaluatorNumericScore
  extends ProofStateAPI.EvaluatorOutputDefinitionBase {
  /** Numeric score output. */
  dataType: "NUMERIC";
  /** Optional inclusive minimum value. */
  minValue?: number;
  /** Optional inclusive maximum value. */
  maxValue?: number;
}
