/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface StringEvaluationRuleFilter {
  /** Column to filter on. */
  column: string;
  operator: ProofStateAPI.EvaluationRuleStringFilterOperator;
  value: string;
}
