/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface StringOptionsEvaluationRuleFilter {
  /** Column to filter on. */
  column: string;
  operator: ProofStateAPI.EvaluationRuleOptionsFilterOperator;
  /** One or more allowed string values. */
  value: string[];
}
