/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface EvaluationRulesPage {
  /** Evaluation rules for this page. */
  data: ProofStateAPI.EvaluationRule[];
  /** Cursor pagination metadata. */
  meta: ProofStateAPI.CursorMeta;
}
