/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface PaginatedAnnotationQueues {
  data: ProofStateAPI.AnnotationQueue[];
  meta: ProofStateAPI.utils.MetaResponse;
}
