/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface PaginatedAnnotationQueueItems {
  data: ProofStateAPI.AnnotationQueueItem[];
  meta: ProofStateAPI.utils.MetaResponse;
}
