/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index.js";
import * as ProofStateAPI from "../../../index.js";
import * as core from "../../../../core/index.js";

export class EvaluationAccessDeniedError extends errors.ProofStateAPIError {
  constructor(
    body: ProofStateAPI.PublicApiError,
    rawResponse?: core.RawResponse,
  ) {
    super({
      message: "EvaluationAccessDeniedError",
      statusCode: 403,
      body: body,
      rawResponse: rawResponse,
    });
    Object.setPrototypeOf(this, EvaluationAccessDeniedError.prototype);
  }
}
