/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index.js";
import * as core from "../../../../core/index.js";

export class FeedbackNotConfiguredError extends errors.ProofStateAPIError {
  constructor(rawResponse?: core.RawResponse) {
    super({
      message: "FeedbackNotConfiguredError",
      statusCode: 409,
      rawResponse: rawResponse,
    });
    Object.setPrototypeOf(this, FeedbackNotConfiguredError.prototype);
  }
}
