/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface PaginatedDatasetRunItems {
  data: ProofStateAPI.DatasetRunItem[];
  meta: ProofStateAPI.utils.MetaResponse;
  _deprecation?: ProofStateAPI.Deprecation;
}
