/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core/index.js";
import * as ProofStateAPI from "../../../index.js";
import {
  mergeHeaders,
  mergeOnlyDefinedHeaders,
} from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Scim {
  export interface Options {
    environment: core.Supplier<string>;
    /** Specify a custom URL to connect the client to. */
    baseUrl?: core.Supplier<string>;
    username?: core.Supplier<string | undefined>;
    password?: core.Supplier<string | undefined>;
    /** Override the X-ProofState-Sdk-Name header */
    xProofStateSdkName?: core.Supplier<string | undefined>;
    /** Override the X-ProofState-Sdk-Version header */
    xProofStateSdkVersion?: core.Supplier<string | undefined>;
    /** Override the X-ProofState-Public-Key header */
    xProofStatePublicKey?: core.Supplier<string | undefined>;
    /** Additional headers to include in requests. */
    headers?: Record<
      string,
      string | core.Supplier<string | null | undefined> | null | undefined
    >;
  }

  export interface RequestOptions {
    /** The maximum time to wait for a response in seconds. */
    timeoutInSeconds?: number;
    /** The number of times to retry the request. Defaults to 2. */
    maxRetries?: number;
    /** A hook to abort the request. */
    abortSignal?: AbortSignal;
    /** Override the X-ProofState-Sdk-Name header */
    xProofStateSdkName?: string | undefined;
    /** Override the X-ProofState-Sdk-Version header */
    xProofStateSdkVersion?: string | undefined;
    /** Override the X-ProofState-Public-Key header */
    xProofStatePublicKey?: string | undefined;
    /** Additional query string parameters to include in the request. */
    queryParams?: Record<string, unknown>;
    /** Additional headers to include in the request. */
    headers?: Record<
      string,
      string | core.Supplier<string | null | undefined> | null | undefined
    >;
  }
}

export class Scim {
  protected readonly _options: Scim.Options;

  constructor(_options: Scim.Options) {
    this._options = _options;
  }

  /**
   * Get SCIM Service Provider Configuration (requires organization-scoped API key)
   *
   * @param {Scim.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.scim.getServiceProviderConfig()
   */
  public getServiceProviderConfig(
    requestOptions?: Scim.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.ServiceProviderConfig> {
    return core.HttpResponsePromise.fromPromise(
      this.__getServiceProviderConfig(requestOptions),
    );
  }

  private async __getServiceProviderConfig(
    requestOptions?: Scim.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.ServiceProviderConfig>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/scim/ServiceProviderConfig",
      ),
      method: "GET",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.ServiceProviderConfig,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/scim/ServiceProviderConfig.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Get SCIM Resource Types (requires organization-scoped API key)
   *
   * @param {Scim.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.scim.getResourceTypes()
   */
  public getResourceTypes(
    requestOptions?: Scim.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.ResourceTypesResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__getResourceTypes(requestOptions),
    );
  }

  private async __getResourceTypes(
    requestOptions?: Scim.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.ResourceTypesResponse>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/scim/ResourceTypes",
      ),
      method: "GET",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.ResourceTypesResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/scim/ResourceTypes.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Get SCIM Schemas (requires organization-scoped API key)
   *
   * @param {Scim.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.scim.getSchemas()
   */
  public getSchemas(
    requestOptions?: Scim.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.SchemasResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__getSchemas(requestOptions),
    );
  }

  private async __getSchemas(
    requestOptions?: Scim.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.SchemasResponse>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/scim/Schemas",
      ),
      method: "GET",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.SchemasResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/scim/Schemas.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * List users in the organization (requires organization-scoped API key)
   *
   * @param {ProofStateAPI.ListUsersRequest} request
   * @param {Scim.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.scim.listUsers()
   */
  public listUsers(
    request: ProofStateAPI.ListUsersRequest = {},
    requestOptions?: Scim.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.ScimUsersListResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__listUsers(request, requestOptions),
    );
  }

  private async __listUsers(
    request: ProofStateAPI.ListUsersRequest = {},
    requestOptions?: Scim.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.ScimUsersListResponse>> {
    const { filter, startIndex, count } = request;
    const _queryParams: Record<
      string,
      string | string[] | object | object[] | null
    > = {};
    if (filter != null) {
      _queryParams["filter"] = filter;
    }

    if (startIndex != null) {
      _queryParams["startIndex"] = startIndex.toString();
    }

    if (count != null) {
      _queryParams["count"] = count.toString();
    }

    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/scim/Users",
      ),
      method: "GET",
      headers: _headers,
      queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.ScimUsersListResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/scim/Users.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Create a new user in the organization (requires organization-scoped API key)
   *
   * @param {ProofStateAPI.CreateUserRequest} request
   * @param {Scim.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.scim.createUser({
   *         userName: "userName",
   *         name: {
   *             formatted: undefined
   *         },
   *         emails: undefined,
   *         active: undefined,
   *         password: undefined
   *     })
   */
  public createUser(
    request: ProofStateAPI.CreateUserRequest,
    requestOptions?: Scim.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.ScimUser> {
    return core.HttpResponsePromise.fromPromise(
      this.__createUser(request, requestOptions),
    );
  }

  private async __createUser(
    request: ProofStateAPI.CreateUserRequest,
    requestOptions?: Scim.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.ScimUser>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/scim/Users",
      ),
      method: "POST",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.ScimUser,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling POST /api/public/scim/Users.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Get a specific user by ID (requires organization-scoped API key)
   *
   * @param {string} userId
   * @param {Scim.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.scim.getUser("userId")
   */
  public getUser(
    userId: string,
    requestOptions?: Scim.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.ScimUser> {
    return core.HttpResponsePromise.fromPromise(
      this.__getUser(userId, requestOptions),
    );
  }

  private async __getUser(
    userId: string,
    requestOptions?: Scim.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.ScimUser>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/scim/Users/${encodeURIComponent(userId)}`,
      ),
      method: "GET",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.ScimUser,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/scim/Users/{userId}.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Remove a user from the organization (requires organization-scoped API key). Note that this only removes the user from the organization but does not delete the user entity itself.
   *
   * @param {string} userId
   * @param {Scim.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.scim.deleteUser("userId")
   */
  public deleteUser(
    userId: string,
    requestOptions?: Scim.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.EmptyResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__deleteUser(userId, requestOptions),
    );
  }

  private async __deleteUser(
    userId: string,
    requestOptions?: Scim.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.EmptyResponse>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/scim/Users/${encodeURIComponent(userId)}`,
      ),
      method: "DELETE",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.EmptyResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling DELETE /api/public/scim/Users/{userId}.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  protected async _getAuthorizationHeader(): Promise<string | undefined> {
    const username = await core.Supplier.get(this._options.username);
    const password = await core.Supplier.get(this._options.password);
    if (username != null && password != null) {
      return core.BasicAuth.toAuthorizationHeader({
        username: username,
        password: password,
      });
    }

    return undefined;
  }
}
