/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface ResourceTypesResponse {
  schemas: string[];
  totalResults: number;
  Resources: ProofStateAPI.ResourceType[];
}
