/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface ResourceType {
  schemas?: string[];
  id: string;
  name: string;
  endpoint: string;
  description: string;
  schema: string;
  schemaExtensions: ProofStateAPI.SchemaExtension[];
  meta: ProofStateAPI.ResourceMeta;
}
