/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface ScimUser {
  schemas: string[];
  id: string;
  userName: string;
  name: ProofStateAPI.ScimName;
  emails: ProofStateAPI.ScimEmail[];
  meta: ProofStateAPI.UserMeta;
}
