/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface ServiceProviderConfig {
  schemas: string[];
  documentationUri: string;
  patch: ProofStateAPI.ScimFeatureSupport;
  bulk: ProofStateAPI.BulkConfig;
  filter: ProofStateAPI.FilterConfig;
  changePassword: ProofStateAPI.ScimFeatureSupport;
  sort: ProofStateAPI.ScimFeatureSupport;
  etag: ProofStateAPI.ScimFeatureSupport;
  authenticationSchemes: ProofStateAPI.AuthenticationScheme[];
  meta: ProofStateAPI.ResourceMeta;
}
