/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface BlobStorageIntegrationResponse {
  id: string;
  projectId: string;
  type: ProofStateAPI.BlobStorageIntegrationType;
  bucketName: string;
  endpoint: string | null;
  region: string;
  accessKeyId: string | null;
  prefix: string;
  exportFrequency: ProofStateAPI.BlobStorageExportFrequency;
  enabled: boolean;
  forcePathStyle: boolean;
  fileType: ProofStateAPI.BlobStorageIntegrationFileTypeResponse;
  exportMode: ProofStateAPI.BlobStorageExportMode;
  exportStartDate: string | null;
  compressed: boolean;
  exportSource: ProofStateAPI.BlobStorageExportSource;
  /** Field groups included in each exported observation row. An empty list is treated as all groups during export. */
  exportFieldGroups: ProofStateAPI.BlobStorageExportFieldGroup[] | null;
  nextSyncAt: string | null;
  lastSyncAt: string | null;
  lastError: string | null;
  lastErrorAt: string | null;
  createdAt: string;
  updatedAt: string;
}
