/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

/**
 * Key-value attribute pair for resources, scopes, or spans
 */
export interface OtelAttribute {
  /** Attribute key (e.g., "service.name", "proofstate.observation.type") */
  key?: string;
  /** Attribute value */
  value?: ProofStateAPI.OtelAttributeValue;
}
