/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

/**
 * Collection of spans from a single instrumentation scope
 */
export interface OtelScopeSpan {
  /** Instrumentation scope information */
  scope?: ProofStateAPI.OtelScope;
  /** Array of spans */
  spans?: ProofStateAPI.OtelSpan[];
}
