/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export type GetScoresResponseData =
  | ProofStateAPI.GetScoresResponseData.Numeric
  | ProofStateAPI.GetScoresResponseData.Categorical
  | ProofStateAPI.GetScoresResponseData.Boolean
  | ProofStateAPI.GetScoresResponseData.Correction
  | ProofStateAPI.GetScoresResponseData.Text;

export namespace GetScoresResponseData {
  export interface Numeric extends ProofStateAPI.GetScoresResponseDataNumeric {
    dataType: "NUMERIC";
  }

  export interface Categorical
    extends ProofStateAPI.GetScoresResponseDataCategorical {
    dataType: "CATEGORICAL";
  }

  export interface Boolean extends ProofStateAPI.GetScoresResponseDataBoolean {
    dataType: "BOOLEAN";
  }

  export interface Correction
    extends ProofStateAPI.GetScoresResponseDataCorrection {
    dataType: "CORRECTION";
  }

  export interface Text extends ProofStateAPI.GetScoresResponseDataText {
    dataType: "TEXT";
  }
}
