/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface ScoreConfigs {
  data: ProofStateAPI.ScoreConfig[];
  meta: ProofStateAPI.utils.MetaResponse;
}
