/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         note: undefined,
 *         publicKey: undefined,
 *         secretKey: undefined
 *     }
 */
export interface CreateApiKeyRequest {
  /** Optional note for the API key */
  note?: string;
  /** Optional predefined public key. New ProofState keys use the 'pk-ps-' prefix. If provided, secretKey must also be provided. */
  publicKey?: string;
  /** Optional predefined secret key. New ProofState keys use the 'sk-ps-' prefix. If provided, publicKey must also be provided. */
  secretKey?: string;
}
