/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../../../index.js";

export interface UpdateDashboardRequest {
  name?: string;
  description?: string;
  definition?: ProofStateAPI.unstable.DashboardDefinition;
  filters?: ProofStateAPI.unstable.DashboardWidgetFilter[];
}
