/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface PaginatedModels {
  data: ProofStateAPI.Model[];
  meta: ProofStateAPI.utils.MetaResponse;
}
