/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface Comment {
  id: string;
  projectId: string;
  createdAt: string;
  updatedAt: string;
  objectType: ProofStateAPI.CommentObjectType;
  objectId: string;
  content: string;
  /** The user ID of the comment author */
  authorUserId?: string | null;
}
