/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface DatasetItemMediaReference {
  /** The dataset item field containing the reference */
  field: ProofStateAPI.DatasetItemMediaReferenceField;
  /** The ProofState media reference string, e.g. `@@@proofstateMedia:type=image/png|id=...|source=bytes@@@` */
  referenceString: string;
  /** JSONPath of the string holding the reference within the field, e.g. `$['image']` */
  jsonPath: string;
  /** The resolved media record. */
  media: ProofStateAPI.DatasetItemMediaReferenceMedia;
}
