/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface DatasetRunWithItems extends ProofStateAPI.DatasetRun {
  datasetRunItems: ProofStateAPI.DatasetRunItem[];
  _deprecation?: ProofStateAPI.Deprecation;
}
