/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

/**
 * Input condition that sums usage details whose keys match a regex.
 */
export interface PricingTierUsageConditionInput {
  /** Regex pattern matched against usage detail keys. */
  usageDetailPattern: string;
  operator: ProofStateAPI.PricingTierOperator;
  /** Numeric threshold for the summed matching usage values. */
  value: number;
  /** Whether the usage-detail regex is case-sensitive. Defaults to false. */
  caseSensitive?: boolean;
}
