/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

/**
 * Condition that matches any configured value for a top-level observation attribute.
 */
export interface PricingTierAttributeCondition {
  /** Observation attribute object evaluated by this condition. */
  source: ProofStateAPI.PricingTierAttributeSource;
  /** Exact top-level attribute key. */
  key: string;
  /** Membership operator. */
  operator: "in";
  /** Accepted string attribute values. At least one value is required. */
  values: string[];
}
