/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

/**
 * Condition input for matching a pricing tier.
 */
export type PricingTierConditionInput =
  | ProofStateAPI.PricingTierUsageConditionInput
  | ProofStateAPI.PricingTierAttributeCondition;
