/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export type ScoreV1 =
  /**
   * Score with NUMERIC data type */
  | ProofStateAPI.ScoreV1.Numeric
  /**
   * Score with CATEGORICAL data type */
  | ProofStateAPI.ScoreV1.Categorical
  /**
   * Score with BOOLEAN data type */
  | ProofStateAPI.ScoreV1.Boolean
  /**
   * Score with TEXT data type */
  | ProofStateAPI.ScoreV1.Text;

export namespace ScoreV1 {
  export interface Numeric extends ProofStateAPI.NumericScoreV1 {
    dataType: "NUMERIC";
  }

  export interface Categorical extends ProofStateAPI.CategoricalScoreV1 {
    dataType: "CATEGORICAL";
  }

  export interface Boolean extends ProofStateAPI.BooleanScoreV1 {
    dataType: "BOOLEAN";
  }

  export interface Text extends ProofStateAPI.TextScoreV1 {
    dataType: "TEXT";
  }
}
