/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export type Score =
  /**
   * Score with NUMERIC data type */
  | ProofStateAPI.Score.Numeric
  /**
   * Score with CATEGORICAL data type */
  | ProofStateAPI.Score.Categorical
  /**
   * Score with BOOLEAN data type */
  | ProofStateAPI.Score.Boolean
  /**
   * Score with CORRECTION data type */
  | ProofStateAPI.Score.Correction
  /**
   * Score with TEXT data type */
  | ProofStateAPI.Score.Text;

export namespace Score {
  export interface Numeric extends ProofStateAPI.NumericScore, _Base {
    dataType: "NUMERIC";
  }

  export interface Categorical extends ProofStateAPI.CategoricalScore, _Base {
    dataType: "CATEGORICAL";
  }

  export interface Boolean extends ProofStateAPI.BooleanScore, _Base {
    dataType: "BOOLEAN";
  }

  export interface Correction extends ProofStateAPI.CorrectionScore, _Base {
    dataType: "CORRECTION";
  }

  export interface Text extends ProofStateAPI.TextScore, _Base {
    dataType: "TEXT";
  }

  export interface _Base {
    _deprecation?: ProofStateAPI.Deprecation;
  }
}
