/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface SessionWithTraces extends ProofStateAPI.Session {
  traces: ProofStateAPI.Trace[];
  _deprecation?: ProofStateAPI.Deprecation;
}
