/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface TextScoreV1 extends ProofStateAPI.BaseScoreV1 {
  /** The text content of the score (1-500 characters) */
  stringValue: string;
}
