/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface TraceWithFullDetails extends ProofStateAPI.Trace {
  /** Path of trace in ProofState UI */
  htmlPath: string;
  /** Latency of trace in seconds */
  latency?: number | null;
  /** Cost of trace in USD */
  totalCost?: number | null;
  /** List of observations */
  observations: ProofStateAPI.ObservationsView[];
  /** List of scores */
  scores: ProofStateAPI.ScoreV1[];
  _deprecation?: ProofStateAPI.Deprecation;
}
