/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface CreateChatPromptRequest {
  name: string;
  prompt: ProofStateAPI.ChatMessageWithPlaceholders[];
  config?: unknown;
  type: ProofStateAPI.CreateChatPromptType;
  /** List of deployment labels of this prompt version. */
  labels?: string[];
  /** List of tags to apply to all versions of this prompt. */
  tags?: string[];
  /** Commit message for this prompt version. */
  commitMessage?: string;
}
