/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export type Prompt = ProofStateAPI.Prompt.Chat | ProofStateAPI.Prompt.Text;

export namespace Prompt {
  export interface Chat extends ProofStateAPI.ChatPrompt {
    type: "chat";
  }

  export interface Text extends ProofStateAPI.TextPrompt {
    type: "text";
  }
}
