/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

/**
 * Initial evaluator definition with metadata and definition fields at the same level. The returned evaluator starts at version `1`.
 */
export type CreateEvaluatorRequest =
  | ProofStateAPI.CreateEvaluatorRequest.LlmAsJudge
  | ProofStateAPI.CreateEvaluatorRequest.Code;

export namespace CreateEvaluatorRequest {
  export interface LlmAsJudge
    extends ProofStateAPI.CreateLlmAsJudgeEvaluatorRequest {
    type: "llm_as_judge";
  }

  export interface Code extends ProofStateAPI.CreateCodeEvaluatorRequest {
    type: "code";
  }
}
