/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface CreateLlmAsJudgeEvaluatorRequest {
  /** Human-readable evaluator name. Names are not identifiers and do not need to be unique. */
  name: string;
  /** Optional human-readable evaluator description. */
  description?: string | null;
  /** Evaluator type. */
  type: "llm_as_judge";
  /** User prompt string shortcut or an ordered list of chat messages. */
  prompt: ProofStateAPI.EvaluatorChatPromptInput;
  /** Explicit model configuration. Set to `null` or omit to use the project's default evaluation model. */
  modelConfig?: ProofStateAPI.EvaluatorModelConfig | null;
  /** Default prompt-variable mapping, or `null` when no default is configured. */
  variableMapping?: ProofStateAPI.PromptVariableMappingInput[] | null;
  /** Structured output schema returned by this evaluator. Do not include an internal persistence version. */
  outputDefinition: ProofStateAPI.EvaluatorOutputDefinition;
}
