/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

/**
 * A user prompt string shortcut, or an ordered list of chat messages.
 */
export type EvaluatorChatPromptInput =
  | string
  | ProofStateAPI.EvaluatorChatPrompt;
