/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface EvaluatorBase {
  /** Stable identifier of this evaluator across all versions. */
  id: string;
  /** Human-readable evaluator name. Names are not identifiers and do not need to be unique. */
  name: string;
  /** Optional human-readable evaluator description. */
  description: string | null;
  /** User who created this evaluator, or `null` when no user can be resolved. */
  createdBy: ProofStateAPI.Creator | null;
  /** Effective evaluator status after ProofState validates its runtime configuration. */
  status: ProofStateAPI.EvaluatorStatus;
  /** Timestamp when the evaluator was paused, otherwise `null`. */
  pausedAt: string | null;
  /** Machine-readable reason when `status=paused`, otherwise `null`. */
  pausedReason: string | null;
  /** Human-readable explanation when `status=paused`, otherwise `null`. */
  pausedMessage: string | null;
  /** All modern and legacy evaluation-rule assignments in newest-assignment-first order. Rule-specific mappings are exposed as `variableMappingOverride`; inherited defaults are omitted. */
  evaluationRuleAssignments: ProofStateAPI.EvaluationRuleAssignment[];
  /** Timestamp when the evaluator was created. */
  createdAt: string;
  /** Timestamp when the evaluator was last updated. */
  updatedAt: string;
  /** Stable identifier of the latest evaluator version. */
  versionId: string;
  /** Monotonically increasing latest evaluator version number. */
  version: number;
  /** Timestamp when the latest evaluator version was created. */
  versionCreatedAt: string;
  /** User who created the latest evaluator version, or `null` when no user can be resolved. */
  versionCreatedBy: ProofStateAPI.Creator | null;
}
