/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

/**
 * One evaluator that can be used for scoring.
 *
 * An evaluator describes **how** to score data. Associated evaluation rules describe **which** live objects should be evaluated.
 */
export type Evaluator =
  | ProofStateAPI.Evaluator.LlmAsJudge
  | ProofStateAPI.Evaluator.Code;

export namespace Evaluator {
  export interface LlmAsJudge extends ProofStateAPI.LlmAsJudgeEvaluator {
    type: "llm_as_judge";
  }

  export interface Code extends ProofStateAPI.CodeEvaluator {
    type: "code";
  }
}
