/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export type EvaluatorVersion =
  | ProofStateAPI.EvaluatorVersion.LlmAsJudge
  | ProofStateAPI.EvaluatorVersion.Code;

export namespace EvaluatorVersion {
  export interface LlmAsJudge extends ProofStateAPI.LlmAsJudgeEvaluatorVersion {
    type: "llm_as_judge";
  }

  export interface Code extends ProofStateAPI.CodeEvaluatorVersion {
    type: "code";
  }
}
