/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface EvaluatorVersionsPage {
  /** Evaluator versions for this page in newest-first order. */
  data: ProofStateAPI.EvaluatorVersion[];
  /** Cursor pagination metadata. */
  meta: ProofStateAPI.CursorMeta;
}
