/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface LlmAsJudgeEvaluator extends ProofStateAPI.EvaluatorBase {
  /** Evaluator type. */
  type: "llm_as_judge";
  /** Ordered chat messages used by the latest evaluator version. */
  prompt: ProofStateAPI.EvaluatorChatPrompt;
  /** Variables extracted from the latest prompt and available for evaluation-rule mappings. */
  variables: string[];
  /** Default variable mapping for the latest version, or `null` when no default is configured. */
  variableMapping: ProofStateAPI.PromptVariableMappingRead[] | null;
  /** Explicit model configuration for the latest version, or `null` when the project's default evaluation model is used. */
  modelConfig: ProofStateAPI.EvaluatorModelConfig | null;
  /** Structured output schema returned by the latest evaluator version. */
  outputDefinition: ProofStateAPI.PublicEvaluatorOutputDefinition;
}
