/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface LlmAsJudgeEvaluatorVersion
  extends ProofStateAPI.EvaluatorVersionBase {
  /** Evaluator type. */
  type: "llm_as_judge";
  /** Ordered chat messages used during evaluation. */
  prompt: ProofStateAPI.EvaluatorChatPrompt;
  /**
   * Variables extracted from the prompt and available for evaluation-rule mappings.
   *
   * Every variable must be mapped exactly once when a rule provides an explicit mapping.
   */
  variables: string[];
  /** Default variable mapping for this evaluator version, or `null` when no default is configured. */
  variableMapping: ProofStateAPI.PromptVariableMappingRead[] | null;
  /** Explicit model configuration, or `null` when the project's default evaluation model is used. */
  modelConfig: ProofStateAPI.EvaluatorModelConfig | null;
  /**
   * Structured output schema returned by this evaluator.
   *
   * Responses include `dataType` and omit the internal output-definition persistence version.
   */
  outputDefinition: ProofStateAPI.PublicEvaluatorOutputDefinition;
}
