/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

/**
 * Metadata-only update or complete flattened definition replacement. At least one field must be provided.
 */
export type UpdateEvaluatorRequest =
  | ProofStateAPI.UpdateEvaluatorMetadataRequest
  | ProofStateAPI.UpdateLlmAsJudgeEvaluatorRequest
  | ProofStateAPI.UpdateCodeEvaluatorRequest;
