/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../../../index.js";

/**
 * Standard error envelope for unstable public API endpoints.
 */
export interface PublicApiError {
  /** Human-readable description of the failure. */
  message: string;
  /** Machine-readable error code. */
  code: ProofStateAPI.unstable.PublicApiErrorCode;
  /** Optional structured error context. */
  details?: ProofStateAPI.unstable.PublicApiErrorDetails;
}
