/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../../../core/index.js";
import * as ProofStateAPI from "../../../../../index.js";
import {
  mergeHeaders,
  mergeOnlyDefinedHeaders,
} from "../../../../../../core/headers.js";
import * as errors from "../../../../../../errors/index.js";

export declare namespace DashboardWidgets {
  export interface Options {
    environment: core.Supplier<string>;
    /** Specify a custom URL to connect the client to. */
    baseUrl?: core.Supplier<string>;
    username?: core.Supplier<string | undefined>;
    password?: core.Supplier<string | undefined>;
    /** Override the X-ProofState-Sdk-Name header */
    xProofStateSdkName?: core.Supplier<string | undefined>;
    /** Override the X-ProofState-Sdk-Version header */
    xProofStateSdkVersion?: core.Supplier<string | undefined>;
    /** Override the X-ProofState-Public-Key header */
    xProofStatePublicKey?: core.Supplier<string | undefined>;
    /** Additional headers to include in requests. */
    headers?: Record<
      string,
      string | core.Supplier<string | null | undefined> | null | undefined
    >;
  }

  export interface RequestOptions {
    /** The maximum time to wait for a response in seconds. */
    timeoutInSeconds?: number;
    /** The number of times to retry the request. Defaults to 2. */
    maxRetries?: number;
    /** A hook to abort the request. */
    abortSignal?: AbortSignal;
    /** Override the X-ProofState-Sdk-Name header */
    xProofStateSdkName?: string | undefined;
    /** Override the X-ProofState-Sdk-Version header */
    xProofStateSdkVersion?: string | undefined;
    /** Override the X-ProofState-Public-Key header */
    xProofStatePublicKey?: string | undefined;
    /** Additional query string parameters to include in the request. */
    queryParams?: Record<string, unknown>;
    /** Additional headers to include in the request. */
    headers?: Record<
      string,
      string | core.Supplier<string | null | undefined> | null | undefined
    >;
  }
}

export class DashboardWidgets {
  protected readonly _options: DashboardWidgets.Options;

  constructor(_options: DashboardWidgets.Options) {
    this._options = _options;
  }

  /**
   * List dashboard widgets in the project, ordered by most recently
   * updated first.
   *
   * Responses may include legacy `traces` widgets created before this
   * API existed. New widgets cannot be created with `view: traces`.
   *
   * @param {ProofStateAPI.unstable.ListDashboardWidgetsRequest} request
   * @param {DashboardWidgets.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.unstable.BadRequestError}
   * @throws {@link ProofStateAPI.unstable.UnauthorizedError}
   * @throws {@link ProofStateAPI.unstable.AccessDeniedError}
   * @throws {@link ProofStateAPI.unstable.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.unstable.TooManyRequestsError}
   * @throws {@link ProofStateAPI.unstable.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.dashboardWidgets.list()
   */
  public list(
    request: ProofStateAPI.unstable.ListDashboardWidgetsRequest = {},
    requestOptions?: DashboardWidgets.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.unstable.DashboardWidgetList> {
    return core.HttpResponsePromise.fromPromise(
      this.__list(request, requestOptions),
    );
  }

  private async __list(
    request: ProofStateAPI.unstable.ListDashboardWidgetsRequest = {},
    requestOptions?: DashboardWidgets.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.unstable.DashboardWidgetList>> {
    const { page, limit } = request;
    const _queryParams: Record<
      string,
      string | string[] | object | object[] | null
    > = {};
    if (page != null) {
      _queryParams["page"] = page.toString();
    }

    if (limit != null) {
      _queryParams["limit"] = limit.toString();
    }

    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/unstable/dashboard-widgets",
      ),
      method: "GET",
      headers: _headers,
      queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.unstable.DashboardWidgetList,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.unstable.BadRequestError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.unstable.UnauthorizedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.unstable.AccessDeniedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.unstable.MethodNotAllowedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.unstable.TooManyRequestsError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.unstable.InternalServerError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/unstable/dashboard-widgets.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Create a dashboard widget (a standalone chart definition you place on
   * any dashboard).
   *
   * This endpoint creates the widget only; place it on a dashboard via
   * `POST /dashboards/{dashboardId}/placements`.
   *
   * Supported views are `observations`, `scores-numeric`, `scores-boolean`, and `scores-categorical`.
   * The legacy `traces` view is not supported by this unstable API.
   * Widgets are created as v2 internally.
   *
   * `chartConfig` is optional and defaults to the plain config for
   * `chartType`; when `chartConfig.type` is given it must match
   * `chartType`.
   *
   * Unstable API note:
   * - This surface may evolve while dashboard/widget APIs are being finalized.
   *
   * @param {ProofStateAPI.unstable.CreateDashboardWidgetRequest} request
   * @param {DashboardWidgets.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.unstable.BadRequestError}
   * @throws {@link ProofStateAPI.unstable.UnauthorizedError}
   * @throws {@link ProofStateAPI.unstable.AccessDeniedError}
   * @throws {@link ProofStateAPI.unstable.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.unstable.TooManyRequestsError}
   * @throws {@link ProofStateAPI.unstable.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.dashboardWidgets.create({
   *         name: "Total cost by model",
   *         description: "Total model cost grouped by provided model name.",
   *         view: "observations",
   *         dimensions: [{
   *                 field: "providedModelName"
   *             }],
   *         metrics: [{
   *                 measure: "totalCost",
   *                 agg: "sum"
   *             }],
   *         filters: [],
   *         chartType: "HORIZONTAL_BAR",
   *         chartConfig: {
   *             row_limit: 10
   *         }
   *     })
   */
  public create(
    request: ProofStateAPI.unstable.CreateDashboardWidgetRequest,
    requestOptions?: DashboardWidgets.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.unstable.DashboardWidget> {
    return core.HttpResponsePromise.fromPromise(
      this.__create(request, requestOptions),
    );
  }

  private async __create(
    request: ProofStateAPI.unstable.CreateDashboardWidgetRequest,
    requestOptions?: DashboardWidgets.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.unstable.DashboardWidget>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/unstable/dashboard-widgets",
      ),
      method: "POST",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.unstable.DashboardWidget,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.unstable.BadRequestError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.unstable.UnauthorizedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.unstable.AccessDeniedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.unstable.MethodNotAllowedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.unstable.TooManyRequestsError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.unstable.InternalServerError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling POST /api/public/unstable/dashboard-widgets.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Get a dashboard widget by id.
   *
   * The response may use `view: traces` for legacy widgets.
   *
   * @param {string} widgetId
   * @param {DashboardWidgets.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.unstable.BadRequestError}
   * @throws {@link ProofStateAPI.unstable.UnauthorizedError}
   * @throws {@link ProofStateAPI.unstable.AccessDeniedError}
   * @throws {@link ProofStateAPI.unstable.NotFoundError}
   * @throws {@link ProofStateAPI.unstable.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.unstable.TooManyRequestsError}
   * @throws {@link ProofStateAPI.unstable.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.dashboardWidgets.get("widgetId")
   */
  public get(
    widgetId: string,
    requestOptions?: DashboardWidgets.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.unstable.DashboardWidget> {
    return core.HttpResponsePromise.fromPromise(
      this.__get(widgetId, requestOptions),
    );
  }

  private async __get(
    widgetId: string,
    requestOptions?: DashboardWidgets.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.unstable.DashboardWidget>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/unstable/dashboard-widgets/${encodeURIComponent(widgetId)}`,
      ),
      method: "GET",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.unstable.DashboardWidget,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.unstable.BadRequestError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.unstable.UnauthorizedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.unstable.AccessDeniedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.unstable.NotFoundError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.unstable.MethodNotAllowedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.unstable.TooManyRequestsError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.unstable.InternalServerError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/unstable/dashboard-widgets/{widgetId}.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Update a dashboard widget.
   *
   * All fields are optional; at least one field is required.
   * Changing `chartType` without sending `chartConfig` resets the config
   * to the new chart type's defaults. When `chartConfig.type` is given
   * it must match the widget's (possibly updated) `chartType`.
   *
   * `view` cannot be changed to the legacy `traces` value. Existing
   * `traces` widgets may be updated on other fields.
   *
   * @param {string} widgetId
   * @param {ProofStateAPI.unstable.UpdateDashboardWidgetRequest} request
   * @param {DashboardWidgets.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.unstable.BadRequestError}
   * @throws {@link ProofStateAPI.unstable.UnauthorizedError}
   * @throws {@link ProofStateAPI.unstable.AccessDeniedError}
   * @throws {@link ProofStateAPI.unstable.NotFoundError}
   * @throws {@link ProofStateAPI.unstable.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.unstable.TooManyRequestsError}
   * @throws {@link ProofStateAPI.unstable.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.dashboardWidgets.update("widgetId", {
   *         name: undefined,
   *         description: undefined,
   *         view: undefined,
   *         dimensions: undefined,
   *         metrics: undefined,
   *         filters: undefined,
   *         chartType: undefined,
   *         chartConfig: undefined
   *     })
   */
  public update(
    widgetId: string,
    request: ProofStateAPI.unstable.UpdateDashboardWidgetRequest,
    requestOptions?: DashboardWidgets.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.unstable.DashboardWidget> {
    return core.HttpResponsePromise.fromPromise(
      this.__update(widgetId, request, requestOptions),
    );
  }

  private async __update(
    widgetId: string,
    request: ProofStateAPI.unstable.UpdateDashboardWidgetRequest,
    requestOptions?: DashboardWidgets.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.unstable.DashboardWidget>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/unstable/dashboard-widgets/${encodeURIComponent(widgetId)}`,
      ),
      method: "PATCH",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.unstable.DashboardWidget,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.unstable.BadRequestError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.unstable.UnauthorizedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.unstable.AccessDeniedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.unstable.NotFoundError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.unstable.MethodNotAllowedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.unstable.TooManyRequestsError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.unstable.InternalServerError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling PATCH /api/public/unstable/dashboard-widgets/{widgetId}.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Delete a dashboard widget.
   *
   * The API returns `409` while the widget is still placed on a dashboard.
   * Remove those placements first.
   *
   * @param {string} widgetId
   * @param {DashboardWidgets.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.unstable.BadRequestError}
   * @throws {@link ProofStateAPI.unstable.UnauthorizedError}
   * @throws {@link ProofStateAPI.unstable.AccessDeniedError}
   * @throws {@link ProofStateAPI.unstable.NotFoundError}
   * @throws {@link ProofStateAPI.unstable.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.unstable.ConflictError}
   * @throws {@link ProofStateAPI.unstable.TooManyRequestsError}
   * @throws {@link ProofStateAPI.unstable.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.dashboardWidgets.delete("widgetId")
   */
  public delete(
    widgetId: string,
    requestOptions?: DashboardWidgets.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.unstable.DeleteDashboardWidgetResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__delete(widgetId, requestOptions),
    );
  }

  private async __delete(
    widgetId: string,
    requestOptions?: DashboardWidgets.RequestOptions,
  ): Promise<
    core.WithRawResponse<ProofStateAPI.unstable.DeleteDashboardWidgetResponse>
  > {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/unstable/dashboard-widgets/${encodeURIComponent(widgetId)}`,
      ),
      method: "DELETE",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.unstable.DeleteDashboardWidgetResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.unstable.BadRequestError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.unstable.UnauthorizedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.unstable.AccessDeniedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.unstable.NotFoundError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.unstable.MethodNotAllowedError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 409:
          throw new ProofStateAPI.unstable.ConflictError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.unstable.TooManyRequestsError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.unstable.InternalServerError(
            _response.error.body as ProofStateAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling DELETE /api/public/unstable/dashboard-widgets/{widgetId}.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  protected async _getAuthorizationHeader(): Promise<string | undefined> {
    const username = await core.Supplier.get(this._options.username);
    const password = await core.Supplier.get(this._options.password);
    if (username != null && password != null) {
      return core.BasicAuth.toAuthorizationHeader({
        username: username,
        password: password,
      });
    }

    return undefined;
  }
}
