/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../../../index.js";

export interface DashboardWidgetMetric {
  measure: string;
  agg: ProofStateAPI.unstable.DashboardWidgetMetricAggregation;
}
