/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../../../index.js";

export interface DashboardWidgetList {
  data: ProofStateAPI.unstable.DashboardWidget[];
  meta: ProofStateAPI.utils.MetaResponse;
}
