/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../../../index.js";

/**
 * Input-side chart config. `type` is optional and defaults to the
 * widget's `chartType`; when given it must match.
 */
export interface DashboardWidgetChartConfigInput {
  type?: ProofStateAPI.unstable.DashboardWidgetChartType;
  row_limit?: number;
  show_value_labels?: boolean;
  bins?: number;
  defaultSort?: ProofStateAPI.unstable.DashboardWidgetDefaultSort;
}
