/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../../../index.js";

export interface UpdateDashboardWidgetRequest {
  name?: string;
  description?: string;
  view?: ProofStateAPI.unstable.DashboardWidgetView;
  dimensions?: ProofStateAPI.unstable.DashboardWidgetDimension[];
  metrics?: ProofStateAPI.unstable.DashboardWidgetMetric[];
  filters?: ProofStateAPI.unstable.DashboardWidgetFilter[];
  chartType?: ProofStateAPI.unstable.DashboardWidgetChartType;
  chartConfig?: ProofStateAPI.unstable.DashboardWidgetChartConfigInput;
}
