/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface BooleanScoreV3 extends ProofStateAPI.BaseScoreV3 {
  /** The boolean value of the score. */
  value: boolean;
}
