/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface CorrectionScoreV3 extends ProofStateAPI.BaseScoreV3 {
  /** The correction content of the score. Empty string if not set. */
  value: string;
}
