/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface GetScoresV3Response {
  data: ProofStateAPI.ScoreV3[];
  meta: ProofStateAPI.GetScoresV3Meta;
}
