/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

/**
 * A reference to the entity this score is attached to. Discriminated by "kind" — one of trace, observation, session, or experiment.
 */
export type ScoreSubjectV3 =
  /**
   * Subject is a trace-level score. */
  | ProofStateAPI.ScoreSubjectV3.Trace
  /**
   * Subject is an observation-level score scoped to a trace. */
  | ProofStateAPI.ScoreSubjectV3.Observation
  /**
   * Subject is a session-level score. */
  | ProofStateAPI.ScoreSubjectV3.Session
  /**
   * Subject is a dataset run (experiment) score. */
  | ProofStateAPI.ScoreSubjectV3.Experiment;

export namespace ScoreSubjectV3 {
  export interface Trace extends ProofStateAPI.ScoreSubjectTraceV3 {
    kind: "trace";
  }

  export interface Observation extends ProofStateAPI.ScoreSubjectObservationV3 {
    kind: "observation";
  }

  export interface Session extends ProofStateAPI.ScoreSubjectSessionV3 {
    kind: "session";
  }

  export interface Experiment extends ProofStateAPI.ScoreSubjectExperimentV3 {
    kind: "experiment";
  }
}
