/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

/**
 * Standard error response for the stable evaluators and evaluation-rules API.
 *
 * Use the HTTP status for the broad failure class and `code` for programmatic handling. `details` is included when field-level validation or retry information is available.
 *
 * @example
 *     {
 *         message: "Invalid request body",
 *         code: ProofStateAPI.PublicApiErrorCode.InvalidBody,
 *         details: {
 *             issues: [{
 *                     code: "invalid_type",
 *                     message: "Invalid input",
 *                     path: ["definition"]
 *                 }]
 *         }
 *     }
 *
 * @example
 *     {
 *         message: "Evaluator not found",
 *         code: ProofStateAPI.PublicApiErrorCode.ResourceNotFound
 *     }
 *
 * @example
 *     {
 *         message: "Rate limit exceeded",
 *         code: ProofStateAPI.PublicApiErrorCode.RateLimited,
 *         details: {
 *             retryAfterSeconds: 60,
 *             limit: 1000,
 *             remaining: 0,
 *             resetAt: "2026-03-30T10:00:00.000Z"
 *         }
 *     }
 */
export interface PublicApiError {
  /** Human-readable description of the failure. */
  message: string;
  /** Stable machine-readable error code. */
  code: ProofStateAPI.PublicApiErrorCode;
  /** Optional structured validation or rate-limit context. */
  details?: ProofStateAPI.PublicApiErrorDetails;
}
