/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface CreateGenerationEvent extends ProofStateAPI.BaseEvent {
  body: ProofStateAPI.CreateGenerationBody;
}
