/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export type IngestionUsage = ProofStateAPI.Usage | ProofStateAPI.OpenAiUsage;
