/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export type IngestionEvent =
  /**
   * Creates a new trace. Upserts on id for updates if trace with id exists. */
  | ProofStateAPI.IngestionEvent.TraceCreate
  /**
   * Creates a new score. Upserts on id for updates if score with id exists. */
  | ProofStateAPI.IngestionEvent.ScoreCreate
  /**
   * Creates a new span. */
  | ProofStateAPI.IngestionEvent.SpanCreate
  /**
   * Updates span based on id. */
  | ProofStateAPI.IngestionEvent.SpanUpdate
  /**
   * Creates a new generation. */
  | ProofStateAPI.IngestionEvent.GenerationCreate
  /**
   * Updates a generation based on id. */
  | ProofStateAPI.IngestionEvent.GenerationUpdate
  /**
   * Creates an event. */
  | ProofStateAPI.IngestionEvent.EventCreate
  /**
   * Compatible SDKs only, used for debugging purposes. */
  | ProofStateAPI.IngestionEvent.SdkLog
  /**
   * Deprecated event type */
  | ProofStateAPI.IngestionEvent.ObservationCreate
  /**
   * Deprecated event type */
  | ProofStateAPI.IngestionEvent.ObservationUpdate;

export namespace IngestionEvent {
  export interface TraceCreate extends ProofStateAPI.TraceEvent {
    type: "trace-create";
  }

  export interface ScoreCreate extends ProofStateAPI.ScoreEvent {
    type: "score-create";
  }

  export interface SpanCreate extends ProofStateAPI.CreateSpanEvent {
    type: "span-create";
  }

  export interface SpanUpdate extends ProofStateAPI.UpdateSpanEvent {
    type: "span-update";
  }

  export interface GenerationCreate
    extends ProofStateAPI.CreateGenerationEvent {
    type: "generation-create";
  }

  export interface GenerationUpdate
    extends ProofStateAPI.UpdateGenerationEvent {
    type: "generation-update";
  }

  export interface EventCreate extends ProofStateAPI.CreateEventEvent {
    type: "event-create";
  }

  export interface SdkLog extends ProofStateAPI.SdkLogEvent {
    type: "sdk-log";
  }

  export interface ObservationCreate
    extends ProofStateAPI.CreateObservationEvent {
    type: "observation-create";
  }

  export interface ObservationUpdate
    extends ProofStateAPI.UpdateObservationEvent {
    type: "observation-update";
  }
}
