/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface UpdateGenerationBody extends ProofStateAPI.UpdateSpanBody {
  completionStartTime?: string;
  model?: string;
  modelParameters?: Record<string, ProofStateAPI.MapValue>;
  usage?: ProofStateAPI.IngestionUsage;
  promptName?: string;
  usageDetails?: ProofStateAPI.UsageDetails;
  costDetails?: Record<string, number>;
  promptVersion?: number;
}
