/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export type UsageDetails =
  | Record<string, number>
  | ProofStateAPI.OpenAiCompletionUsageSchema
  | ProofStateAPI.OpenAiResponseUsageSchema;
