/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ProofStateAPI from "../../../index.js";

export interface PaginatedDatasetItems {
  data: ProofStateAPI.DatasetItem[];
  meta: ProofStateAPI.utils.MetaResponse;
}
