/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core/index.js";
import * as ProofStateAPI from "../../../index.js";
import {
  mergeHeaders,
  mergeOnlyDefinedHeaders,
} from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace EvaluationRules {
  export interface Options {
    environment: core.Supplier<string>;
    /** Specify a custom URL to connect the client to. */
    baseUrl?: core.Supplier<string>;
    username?: core.Supplier<string | undefined>;
    password?: core.Supplier<string | undefined>;
    /** Override the X-ProofState-Sdk-Name header */
    xProofStateSdkName?: core.Supplier<string | undefined>;
    /** Override the X-ProofState-Sdk-Version header */
    xProofStateSdkVersion?: core.Supplier<string | undefined>;
    /** Override the X-ProofState-Public-Key header */
    xProofStatePublicKey?: core.Supplier<string | undefined>;
    /** Additional headers to include in requests. */
    headers?: Record<
      string,
      string | core.Supplier<string | null | undefined> | null | undefined
    >;
  }

  export interface RequestOptions {
    /** The maximum time to wait for a response in seconds. */
    timeoutInSeconds?: number;
    /** The number of times to retry the request. Defaults to 2. */
    maxRetries?: number;
    /** A hook to abort the request. */
    abortSignal?: AbortSignal;
    /** Override the X-ProofState-Sdk-Name header */
    xProofStateSdkName?: string | undefined;
    /** Override the X-ProofState-Sdk-Version header */
    xProofStateSdkVersion?: string | undefined;
    /** Override the X-ProofState-Public-Key header */
    xProofStatePublicKey?: string | undefined;
    /** Additional query string parameters to include in the request. */
    queryParams?: Record<string, unknown>;
    /** Additional headers to include in the request. */
    headers?: Record<
      string,
      string | core.Supplier<string | null | undefined> | null | undefined
    >;
  }
}

export class EvaluationRules {
  protected readonly _options: EvaluationRules.Options;

  constructor(_options: EvaluationRules.Options) {
    this._options = _options;
  }

  /**
   * Create an evaluation rule using stable evaluator identifiers.
   *
   * An evaluation rule defines **which** incoming observations should be evaluated and how prompt variables should be populated.
   *
   * Key behavior:
   * - rule names are not identifiers and do not need to be unique
   * - rules always use the latest version of each associated evaluator
   * - an enabled rule requires at least one evaluator assignment
   * - omit `sampling` to evaluate every matching observation
   * - omit `filter` to match every incoming observation
   * - `datasetId` is the public filter name for selecting experiment datasets
   *
   * @param {ProofStateAPI.CreateEvaluationRuleRequest} request
   * @param {EvaluationRules.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.BadRequestError}
   * @throws {@link ProofStateAPI.EvaluationUnauthorizedError}
   * @throws {@link ProofStateAPI.EvaluationAccessDeniedError}
   * @throws {@link ProofStateAPI.EvaluationNotFoundError}
   * @throws {@link ProofStateAPI.EvaluationMethodNotAllowedError}
   * @throws {@link ProofStateAPI.ConflictError}
   * @throws {@link ProofStateAPI.TooManyRequestsError}
   * @throws {@link ProofStateAPI.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.evaluationRules.create({
   *         name: "name",
   *         enabled: true,
   *         sampling: undefined,
   *         filter: undefined,
   *         evaluatorAssignments: [{
   *                 evaluatorId: "evaluatorId",
   *                 variableMapping: undefined
   *             }, {
   *                 evaluatorId: "evaluatorId",
   *                 variableMapping: undefined
   *             }]
   *     })
   */
  public create(
    request: ProofStateAPI.CreateEvaluationRuleRequest,
    requestOptions?: EvaluationRules.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.EvaluationRule> {
    return core.HttpResponsePromise.fromPromise(
      this.__create(request, requestOptions),
    );
  }

  private async __create(
    request: ProofStateAPI.CreateEvaluationRuleRequest,
    requestOptions?: EvaluationRules.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.EvaluationRule>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/v2/evaluation-rules",
      ),
      method: "POST",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.EvaluationRule,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.BadRequestError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.EvaluationUnauthorizedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.EvaluationAccessDeniedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.EvaluationNotFoundError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.EvaluationMethodNotAllowedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 409:
          throw new ProofStateAPI.ConflictError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.TooManyRequestsError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.InternalServerError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling POST /api/public/v2/evaluation-rules.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * List evaluation rules in newest-first creation order.
   *
   * This includes legacy trace and dataset rules so they can be inspected and migrated. Treat the cursor as opaque and return it unchanged.
   *
   * @param {ProofStateAPI.ListEvaluationRulesRequest} request
   * @param {EvaluationRules.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.BadRequestError}
   * @throws {@link ProofStateAPI.EvaluationUnauthorizedError}
   * @throws {@link ProofStateAPI.EvaluationAccessDeniedError}
   * @throws {@link ProofStateAPI.EvaluationMethodNotAllowedError}
   * @throws {@link ProofStateAPI.TooManyRequestsError}
   * @throws {@link ProofStateAPI.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.evaluationRules.list()
   */
  public list(
    request: ProofStateAPI.ListEvaluationRulesRequest = {},
    requestOptions?: EvaluationRules.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.EvaluationRulesPage> {
    return core.HttpResponsePromise.fromPromise(
      this.__list(request, requestOptions),
    );
  }

  private async __list(
    request: ProofStateAPI.ListEvaluationRulesRequest = {},
    requestOptions?: EvaluationRules.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.EvaluationRulesPage>> {
    const { limit, cursor } = request;
    const _queryParams: Record<
      string,
      string | string[] | object | object[] | null
    > = {};
    if (limit != null) {
      _queryParams["limit"] = limit.toString();
    }

    if (cursor != null) {
      _queryParams["cursor"] = cursor;
    }

    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/v2/evaluation-rules",
      ),
      method: "GET",
      headers: _headers,
      queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.EvaluationRulesPage,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.BadRequestError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.EvaluationUnauthorizedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.EvaluationAccessDeniedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.EvaluationMethodNotAllowedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.TooManyRequestsError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.InternalServerError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/v2/evaluation-rules.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Get one evaluation rule, including a legacy trace or dataset rule, by its stable identifier.
   *
   * @param {string} evaluationRuleId - Stable evaluation-rule identifier returned by the evaluation-rule endpoints.
   * @param {EvaluationRules.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.EvaluationUnauthorizedError}
   * @throws {@link ProofStateAPI.EvaluationAccessDeniedError}
   * @throws {@link ProofStateAPI.EvaluationNotFoundError}
   * @throws {@link ProofStateAPI.EvaluationMethodNotAllowedError}
   * @throws {@link ProofStateAPI.TooManyRequestsError}
   * @throws {@link ProofStateAPI.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.evaluationRules.get("evaluationRuleId")
   */
  public get(
    evaluationRuleId: string,
    requestOptions?: EvaluationRules.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.EvaluationRule> {
    return core.HttpResponsePromise.fromPromise(
      this.__get(evaluationRuleId, requestOptions),
    );
  }

  private async __get(
    evaluationRuleId: string,
    requestOptions?: EvaluationRules.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.EvaluationRule>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/v2/evaluation-rules/${encodeURIComponent(evaluationRuleId)}`,
      ),
      method: "GET",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.EvaluationRule,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 401:
          throw new ProofStateAPI.EvaluationUnauthorizedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.EvaluationAccessDeniedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.EvaluationNotFoundError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.EvaluationMethodNotAllowedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.TooManyRequestsError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.InternalServerError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/v2/evaluation-rules/{evaluationRuleId}.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Update an evaluation rule by its stable identifier.
   *
   * Provide only the fields to change. Providing `evaluatorAssignments` replaces the complete assignment list. Replacing the list with an empty array disables the rule. Setting `enabled=true` is rejected when the resulting assignment list is empty, including when both fields are sent in the same request.
   *
   * Legacy trace and dataset rules follow the existing lifecycle restrictions: they can be deactivated with `enabled=false`, but their name, filters, sampling, and evaluator assignments cannot be changed.
   *
   * @param {string} evaluationRuleId - Stable evaluation-rule identifier returned by the evaluation-rule endpoints.
   * @param {ProofStateAPI.UpdateEvaluationRuleRequest} request
   * @param {EvaluationRules.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.BadRequestError}
   * @throws {@link ProofStateAPI.EvaluationUnauthorizedError}
   * @throws {@link ProofStateAPI.EvaluationAccessDeniedError}
   * @throws {@link ProofStateAPI.EvaluationNotFoundError}
   * @throws {@link ProofStateAPI.EvaluationMethodNotAllowedError}
   * @throws {@link ProofStateAPI.ConflictError}
   * @throws {@link ProofStateAPI.TooManyRequestsError}
   * @throws {@link ProofStateAPI.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.evaluationRules.update("evaluationRuleId", {
   *         name: undefined,
   *         enabled: undefined,
   *         sampling: undefined,
   *         filter: undefined,
   *         evaluatorAssignments: undefined
   *     })
   */
  public update(
    evaluationRuleId: string,
    request: ProofStateAPI.UpdateEvaluationRuleRequest,
    requestOptions?: EvaluationRules.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.EvaluationRule> {
    return core.HttpResponsePromise.fromPromise(
      this.__update(evaluationRuleId, request, requestOptions),
    );
  }

  private async __update(
    evaluationRuleId: string,
    request: ProofStateAPI.UpdateEvaluationRuleRequest,
    requestOptions?: EvaluationRules.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.EvaluationRule>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/v2/evaluation-rules/${encodeURIComponent(evaluationRuleId)}`,
      ),
      method: "PATCH",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.EvaluationRule,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ProofStateAPI.BadRequestError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.EvaluationUnauthorizedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.EvaluationAccessDeniedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.EvaluationNotFoundError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.EvaluationMethodNotAllowedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 409:
          throw new ProofStateAPI.ConflictError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.TooManyRequestsError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.InternalServerError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling PATCH /api/public/v2/evaluation-rules/{evaluationRuleId}.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Delete an evaluation rule.
   *
   * This removes the live-ingestion rule only. It does not delete associated evaluators or scores already produced by them.
   *
   * Legacy trace and dataset rules can also be deleted. Their evaluators and previously produced scores are preserved.
   *
   * @param {string} evaluationRuleId - Stable evaluation-rule identifier returned by the evaluation-rule endpoints.
   * @param {EvaluationRules.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ProofStateAPI.EvaluationUnauthorizedError}
   * @throws {@link ProofStateAPI.EvaluationAccessDeniedError}
   * @throws {@link ProofStateAPI.EvaluationNotFoundError}
   * @throws {@link ProofStateAPI.EvaluationMethodNotAllowedError}
   * @throws {@link ProofStateAPI.TooManyRequestsError}
   * @throws {@link ProofStateAPI.InternalServerError}
   * @throws {@link ProofStateAPI.Error}
   * @throws {@link ProofStateAPI.UnauthorizedError}
   * @throws {@link ProofStateAPI.AccessDeniedError}
   * @throws {@link ProofStateAPI.MethodNotAllowedError}
   * @throws {@link ProofStateAPI.NotFoundError}
   *
   * @example
   *     await client.evaluationRules.delete("evaluationRuleId")
   */
  public delete(
    evaluationRuleId: string,
    requestOptions?: EvaluationRules.RequestOptions,
  ): core.HttpResponsePromise<ProofStateAPI.DeletedEvaluationRule> {
    return core.HttpResponsePromise.fromPromise(
      this.__delete(evaluationRuleId, requestOptions),
    );
  }

  private async __delete(
    evaluationRuleId: string,
    requestOptions?: EvaluationRules.RequestOptions,
  ): Promise<core.WithRawResponse<ProofStateAPI.DeletedEvaluationRule>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ProofState-Sdk-Name":
          requestOptions?.xProofStateSdkName ??
          this._options?.xProofStateSdkName,
        "X-ProofState-Sdk-Version":
          requestOptions?.xProofStateSdkVersion ??
          this._options?.xProofStateSdkVersion,
        "X-ProofState-Public-Key":
          requestOptions?.xProofStatePublicKey ??
          this._options?.xProofStatePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/v2/evaluation-rules/${encodeURIComponent(evaluationRuleId)}`,
      ),
      method: "DELETE",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ProofStateAPI.DeletedEvaluationRule,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 401:
          throw new ProofStateAPI.EvaluationUnauthorizedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.EvaluationAccessDeniedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.EvaluationNotFoundError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.EvaluationMethodNotAllowedError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new ProofStateAPI.TooManyRequestsError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new ProofStateAPI.InternalServerError(
            _response.error.body as ProofStateAPI.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new ProofStateAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ProofStateAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ProofStateAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ProofStateAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ProofStateAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ProofStateAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ProofStateAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ProofStateAPITimeoutError(
          "Timeout exceeded when calling DELETE /api/public/v2/evaluation-rules/{evaluationRuleId}.",
        );
      case "unknown":
        throw new errors.ProofStateAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  protected async _getAuthorizationHeader(): Promise<string | undefined> {
    const username = await core.Supplier.get(this._options.username);
    const password = await core.Supplier.get(this._options.password);
    if (username != null && password != null) {
      return core.BasicAuth.toAuthorizationHeader({
        username: username,
        password: password,
      });
    }

    return undefined;
  }
}
